# Generated by Django 5.2.4 on 2026-07-01 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('practice', 'Practice')], default='practice', max_length=10)),
                ('category', models.CharField(choices=[('arrays', 'Arrays'), ('strings', 'Strings'), ('linked_lists', 'Linked Lists'), ('trees', 'Trees'), ('graphs', 'Graphs'), ('dp', 'Dynamic Programming'), ('sorting', 'Sorting'), ('searching', 'Searching'), ('math', 'Math'), ('greedy', 'Greedy'), ('backtracking', 'Backtracking'), ('stacks_queues', 'Stacks & Queues'), ('hash_tables', 'Hash Tables'), ('recursion', 'Recursion'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('time_limit_ms', models.IntegerField(default=2000)),
                ('memory_limit_kb', models.IntegerField(default=262144)),
                ('starter_code', models.JSONField(blank=True, default=dict)),
                ('public_test_cases', models.JSONField(blank=True, default=list)),
                ('hidden_test_cases', models.JSONField(blank=True, default=list)),
                ('solution_code', models.TextField(blank=True, default='')),
                ('solution_explanation', models.TextField(blank=True, default='')),
                ('hints', models.JSONField(blank=True, default=list)),
                ('total_submissions', models.IntegerField(default=0)),
                ('accepted_submissions', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['difficulty', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit', 'Time Limit Exceeded'), ('memory_limit', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error')], default='pending', max_length=20)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('memory_used_kb', models.IntegerField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, default=list)),
                ('total_tests', models.IntegerField(default=0)),
                ('passed_tests', models.IntegerField(default=0)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('compile_output', models.TextField(blank=True, default='')),
                ('ai_review', models.TextField(blank=True, default='')),
                ('code_quality_score', models.IntegerField(default=0)),
                ('complexity_analysis', models.CharField(blank=True, default='', max_length=50)),
                ('optimization_suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coding.codingchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
