import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Map, BookOpen, CheckCircle, BrainCircuit } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import api from '@/lib/api';
import { Card } from '@/components/ui/Card';
import type { StudyPlan } from '@/types';

export default function RoadmapPage() {
  const [searchParams] = useSearchParams();
  const topic = searchParams.get('topic');
  const [plan, setPlan] = useState<StudyPlan | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    const params = topic ? { topic } : {};
    api.get('/users/roadmap/', { params })
      .then((res) => setPlan(res.data))
      .catch(() => setPlan(null))
      .finally(() => setLoading(false));
  }, [topic]);

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="flex items-center gap-4 mb-8">
        <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-emerald-400 to-teal-600 flex items-center justify-center shadow-lg shadow-teal-500/20">
          <Map size={32} className="text-white" />
        </div>
        <div>
          <h1 className="text-3xl font-extrabold text-foreground">
            {topic ? `Roadmap: ${topic}` : 'AI Learning Roadmap'}
          </h1>
          <p className="text-muted-foreground mt-1">
            {topic ? `Personalized study plan generated by AI for ${topic}` : 'Personalized study plan based on your interview performance'}
          </p>
        </div>
      </motion.div>

      {loading ? (
        <Card className="p-12 text-center text-muted-foreground animate-pulse">Generating your personalized roadmap...</Card>
      ) : plan ? (
        <div className="grid md:grid-cols-2 gap-6">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }}>
            <Card className="h-full">
              <h2 className="text-xl font-bold flex items-center gap-2 mb-4">
                <BrainCircuit className="text-rose-500" /> Focus Areas
              </h2>
              <p className="text-sm text-muted-foreground mb-4">
                {topic ? `Core concepts you must master for ${topic}.` : 'We identified these areas as needing improvement based on your recent interviews.'}
              </p>
              <ul className="space-y-3">
                {plan.weak_areas.map((area, idx) => (
                  <li key={idx} className="flex items-center gap-3 p-3 bg-rose-500/10 text-rose-600 dark:text-rose-400 rounded-xl font-medium border border-rose-500/20">
                    <div className="w-2 h-2 rounded-full bg-rose-500" />
                    {area}
                  </li>
                ))}
              </ul>
            </Card>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.2 }}>
            <Card className="h-full">
              <h2 className="text-xl font-bold flex items-center gap-2 mb-4">
                <CheckCircle className="text-emerald-500" /> Daily Practice
              </h2>
              <p className="text-sm text-muted-foreground mb-4">Recommended tasks to build your skills consistently.</p>
              <ul className="space-y-3">
                {plan.daily_tasks.map((task, idx) => (
                  <li key={idx} className="flex items-start gap-3 p-3 bg-muted/50 rounded-xl border border-border">
                    <CheckCircle size={18} className="text-emerald-500 mt-0.5 shrink-0" />
                    <span className="text-foreground font-medium">{task}</span>
                  </li>
                ))}
              </ul>
            </Card>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.3 }} className="md:col-span-2">
            <Card>
              <h2 className="text-xl font-bold flex items-center gap-2 mb-4">
                <BookOpen className="text-indigo-500" /> Recommended Resources
              </h2>
              <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {plan.courses.map((course, idx) => (
                  <a key={idx} href={course.url} target="_blank" rel="noreferrer" className="block p-4 bg-muted/40 rounded-xl hover:bg-muted/80 transition-colors border border-border">
                    <div className="text-xs font-bold text-indigo-500 mb-2 uppercase tracking-wider">{course.type}</div>
                    <h3 className="font-semibold text-foreground">{course.title}</h3>
                  </a>
                ))}
              </div>
            </Card>
          </motion.div>
        </div>
      ) : (
        <Card className="p-12 text-center text-muted-foreground">Could not load roadmap data.</Card>
      )}
    </div>
  );
}
