import { useState } from 'react';
import { motion } from 'framer-motion';
import { useQuery } from '@tanstack/react-query';
import { Map, BookOpen, CheckCircle, BrainCircuit, ExternalLink, Target, Sparkles } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import api from '@/lib/api';
import { Card } from '@/components/ui/Card';

interface CourseItem {
  title: string;
  type?: string;
  url?: string;
  description?: string;
}

interface RoadmapPlan {
  weak_areas: string[];
  daily_tasks: string[];
  courses: (string | CourseItem)[];
}

const defaultCourses: CourseItem[] = [
  {
    title: "System Design Primer",
    type: "Architecture",
    url: "https://github.com/donnemartin/system-design-primer",
    description: "Learn how to design large-scale, highly scalable distributed systems."
  },
  {
    title: "LeetCode 75 Study Plan",
    type: "Algorithms",
    url: "https://leetcode.com/studyplan/leetcode-75/",
    description: "75 essential coding problems covering top technical interview patterns."
  },
  {
    title: "Deep Learning & PyTorch Guide",
    type: "AI & ML",
    url: "https://pytorch.org/tutorials/",
    description: "Hands-on tutorials for model training, optimization, and PyTorch."
  }
];

export default function RoadmapPage() {
  const [searchParams] = useSearchParams();
  const topic = searchParams.get('topic');
  const [completedTasks, setCompletedTasks] = useState<Record<number, boolean>>({});

  // Use Query for instant caching and avoiding reload flashes
  const { data: plan, isLoading: loading } = useQuery<RoadmapPlan>({
    queryKey: ['roadmap-plan', topic || 'default'],
    queryFn: async () => {
      const params = topic ? { topic } : {};
      const res = await api.get('/users/roadmap/', { params });
      return res.data;
    },
    staleTime: 5 * 60 * 1000,
  });

  const toggleTask = (idx: number) => {
    setCompletedTasks(prev => ({ ...prev, [idx]: !prev[idx] }));
  };

  const getCourseData = (course: string | CourseItem, idx: number): CourseItem => {
    if (typeof course === 'object' && course !== null && course.title) {
      return {
        title: course.title,
        type: course.type || 'Resource',
        url: course.url || 'https://github.com/donnemartin/system-design-primer',
        description: course.description || 'Curated learning material for technical interview mastery.'
      };
    }
    const fallback = defaultCourses[idx % defaultCourses.length];
    return {
      title: typeof course === 'string' ? course : fallback.title,
      type: fallback.type,
      url: fallback.url,
      description: fallback.description
    };
  };

  const coursesList = plan?.courses && plan.courses.length > 0 
    ? plan.courses.map((c, i) => getCourseData(c, i))
    : defaultCourses;

  return (
    <div className="w-full max-w-5xl mx-auto space-y-6 pb-12 overflow-hidden min-w-0">
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }} className="flex items-center gap-4 mb-6">
        <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center shadow-lg shadow-emerald-500/20 shrink-0">
          <Map size={28} className="text-white" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 flex-wrap">
            <h1 className="text-2xl md:text-3xl font-extrabold text-foreground tracking-tight truncate">
              {topic ? `Roadmap: ${topic}` : 'AI Learning Roadmap'}
            </h1>
            <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20 flex items-center gap-1 shrink-0">
              <Sparkles size={12} /> AI Powered
            </span>
          </div>
          <p className="text-sm text-muted-foreground mt-1 truncate">
            {topic ? `Personalized study plan generated by AI for ${topic}` : 'Personalized study plan based on your recent interview performance'}
          </p>
        </div>
      </motion.div>

      {loading ? (
        <Card className="p-12 text-center text-muted-foreground animate-pulse flex flex-col items-center justify-center gap-3">
          <Sparkles className="animate-spin text-emerald-500" size={24} />
          <p className="font-medium text-sm">Generating your personalized AI roadmap...</p>
        </Card>
      ) : plan ? (
        <div className="grid md:grid-cols-2 gap-6 w-full min-w-0">
          {/* Focus Areas */}
          <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, delay: 0.1 }} className="min-w-0">
            <Card className="h-full border-border bg-card/60 backdrop-blur-sm overflow-hidden">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-lg font-bold flex items-center gap-2 text-foreground">
                  <BrainCircuit size={20} className="text-rose-500" /> Focus Areas
                </h2>
                <span className="text-xs font-medium text-rose-500 bg-rose-500/10 px-2 py-1 rounded-md border border-rose-500/20 shrink-0">
                  {plan.weak_areas?.length || 0} Priority Topics
                </span>
              </div>
              <p className="text-xs text-muted-foreground mb-4">
                {topic ? `Core concepts you must master for ${topic}.` : 'Identified areas needing improvement based on your mock interview responses.'}
              </p>
              <ul className="space-y-3">
                {plan.weak_areas?.map((area, idx) => (
                  <li key={idx} className="flex items-center justify-between p-3.5 bg-rose-500/5 hover:bg-rose-500/10 text-rose-600 dark:text-rose-400 rounded-xl text-sm font-semibold border border-rose-500/20 transition-all min-w-0">
                    <div className="flex items-center gap-3 min-w-0">
                      <div className="w-2.5 h-2.5 rounded-full bg-rose-500 shrink-0" />
                      <span className="truncate">{area}</span>
                    </div>
                    <Target size={15} className="text-rose-500/60 shrink-0 ml-2" />
                  </li>
                ))}
              </ul>
            </Card>
          </motion.div>

          {/* Daily Practice Tasks */}
          <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, delay: 0.2 }} className="min-w-0">
            <Card className="h-full border-border bg-card/60 backdrop-blur-sm overflow-hidden">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-lg font-bold flex items-center gap-2 text-foreground">
                  <CheckCircle size={20} className="text-emerald-500" /> Daily Practice
                </h2>
                <span className="text-xs font-medium text-emerald-500 bg-emerald-500/10 px-2 py-1 rounded-md border border-emerald-500/20 shrink-0">
                  {Object.values(completedTasks).filter(Boolean).length} / {plan.daily_tasks?.length || 0} Done
                </span>
              </div>
              <p className="text-xs text-muted-foreground mb-4">Recommended tasks to build your technical skills consistently.</p>
              <ul className="space-y-3">
                {plan.daily_tasks?.map((task, idx) => {
                  const isDone = !!completedTasks[idx];
                  return (
                    <li 
                      key={idx} 
                      onClick={() => toggleTask(idx)}
                      className={`flex items-start gap-3 p-3.5 rounded-xl border text-sm transition-all cursor-pointer min-w-0 ${
                        isDone 
                          ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-600 dark:text-emerald-400 line-through opacity-80' 
                          : 'bg-muted/40 hover:bg-muted/80 border-border text-foreground'
                      }`}
                    >
                      <CheckCircle size={18} className={`mt-0.5 shrink-0 transition-colors ${isDone ? 'text-emerald-500' : 'text-muted-foreground'}`} />
                      <span className="font-medium flex-1 break-words min-w-0">{task}</span>
                    </li>
                  );
                })}
              </ul>
            </Card>
          </motion.div>

          {/* Recommended Resources */}
          <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, delay: 0.3 }} className="md:col-span-2 min-w-0 w-full">
            <Card className="border-border bg-card/60 backdrop-blur-sm overflow-hidden w-full">
              <h2 className="text-lg font-bold flex items-center gap-2 mb-1 text-foreground">
                <BookOpen size={20} className="text-indigo-500" /> Recommended Learning Resources
              </h2>
              <p className="text-xs text-muted-foreground mb-5">Curated guides, practice platforms, and courses tailored to your interview preparation.</p>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 w-full min-w-0">
                {coursesList.map((course, idx) => (
                  <a 
                    key={idx} 
                    href={course.url} 
                    target="_blank" 
                    rel="noreferrer" 
                    className="group flex flex-col justify-between p-4 bg-muted/30 hover:bg-indigo-500/10 rounded-xl transition-all duration-200 border border-border hover:border-indigo-500/30 shadow-sm min-w-0 overflow-hidden"
                  >
                    <div className="min-w-0">
                      <div className="flex items-center justify-between mb-2 gap-2">
                        <span className="text-[11px] font-bold text-indigo-500 uppercase tracking-wider bg-indigo-500/10 px-2 py-0.5 rounded-md border border-indigo-500/20 truncate">
                          {course.type}
                        </span>
                        <ExternalLink size={14} className="text-muted-foreground group-hover:text-indigo-500 transition-colors shrink-0" />
                      </div>
                      <h3 className="font-semibold text-foreground text-sm group-hover:text-indigo-500 transition-colors truncate">
                        {course.title}
                      </h3>
                      <p className="text-xs text-muted-foreground mt-1.5 line-clamp-2 leading-relaxed break-words">
                        {course.description}
                      </p>
                    </div>
                    <div className="mt-4 pt-3 border-t border-border/40 flex items-center justify-between text-[11px] font-medium text-indigo-500">
                      <span>Explore Material</span>
                      <span className="group-hover:translate-x-0.5 transition-transform">→</span>
                    </div>
                  </a>
                ))}
              </div>
            </Card>
          </motion.div>
        </div>
      ) : (
        <Card className="p-12 text-center text-muted-foreground">Could not load roadmap data.</Card>
      )}
    </div>
  );
}
