# Generated by Django 5.2.4 on 2026-07-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='study_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
