# Generated by Django 4.2.30 on 2026-08-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonSession',
            fields=[
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('candidate_data', models.JSONField(default=dict)),
                ('conversation_history', models.JSONField(blank=True, default=list)),
                ('covered_days', models.JSONField(blank=True, default=list)),
                ('questions_asked', models.IntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
