# Generated by Django 5.2.4 on 2026-07-01 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('hr', 'HR Interview'), ('technical', 'Technical Interview'), ('coding', 'Coding Interview'), ('behavioral', 'Behavioral Interview'), ('company_specific', 'Company Specific'), ('custom', 'Custom Interview')], max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='setup', max_length=20)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('total_questions', models.IntegerField(default=10)),
                ('language', models.CharField(default='English', max_length=50)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('overall_score', models.FloatField(default=0.0)),
                ('technical_score', models.FloatField(default=0.0)),
                ('communication_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('grammar_score', models.FloatField(default=0.0)),
                ('problem_solving_score', models.FloatField(default=0.0)),
                ('ai_context', models.JSONField(blank=True, default=list)),
                ('current_question_index', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('hr', 'HR'), ('technical', 'Technical'), ('coding', 'Coding'), ('behavioral', 'Behavioral'), ('situational', 'Situational')], default='technical', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('expected_answer_points', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interview')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('technical_accuracy', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('communication', models.FloatField(default=0.0)),
                ('grammar', models.FloatField(default=0.0)),
                ('vocabulary', models.FloatField(default=0.0)),
                ('fluency', models.FloatField(default=0.0)),
                ('relevance', models.FloatField(default=0.0)),
                ('completeness', models.FloatField(default=0.0)),
                ('problem_solving', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True, default='')),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interviews.interviewquestion')),
            ],
        ),
    ]
