# Generated by Django 5.2.4 on 2026-07-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_company_interview_recording_url_companyinterviewset'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='interview_guidelines',
            field=models.TextField(blank=True, default='', help_text='Guideline on question types (e.g., tough DSA, practical projects)'),
        ),
        migrations.AddField(
            model_name='company',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='resume_filter_keywords',
            field=models.TextField(blank=True, default='', help_text='Keywords to accept/reject resumes'),
        ),
        migrations.AddField(
            model_name='interview',
            name='english_fluency_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='english_fluency',
            field=models.FloatField(default=0.0),
        ),
    ]
